In [1]:
# coding: utf-8

import xarray as xr
import numpy as np
import pandas as pd
from glob import glob
import sys
from datetime import datetime
from dateutil.relativedelta import relativedelta
import pickle
import os
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import matplotlib as mpl
import jellyfish

In [7]:
next(os.walk(f'{ff_CTRL}'))[2][0]

'BAGOTVILLE A_QC_CTRL_wrf2d_d01.nc'

In [40]:
f = '/home/cruman/Data/CONUS_I/CONUSI@Stations'
#provinces = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'ON', 'PE', 'QC', 'SK']
provinces = next(os.walk(f'{f}'))[1]
datei = datetime(2000,10,1,0)
datef = datetime(2013,9,30,23)

#arq = open('stations_dist_v2.dat', 'w')
#arq.write('CITY;LAT;LON;PEAK1;PEAK2;NEAR0;NEAR0_P01;NEAR0_P02;MEAN;STD\n')
time = []
di = datetime(2000,10,1,0,0)

sim = 'CTRL'
#sim = 'PGW'

for pv in provinces:
    
    # Empty dataframe to populate later
    df = pd.DataFrame({})
    # Folder of the netcdf files
    ff_CTRL = f"{f}/{pv}/{sim}"
    filename = glob(f"{ff_CTRL}/*nc")[0]
    
    # Name of the file, and removing the spaces and the extension
    fname = next(os.walk(f'{ff_CTRL}'))[2][0].replace(' ','_')[:-3] + f'_{sim}.csv'
    print(filename)
    
    # Opening the netcdf file
    xdata = xr.open_dataset(filename, engine='netcdf4')
    
    # Creating the time dimension, as the original dimension is int
    time = []
    for item in xdata.Time:
        time.append(di + relativedelta(hours=int(item.values))) 
    
    # The data is 4 points around the lat/lon of the station. 
    # Averaging it to just one point
    pr = xdata.PREC_ACC_NC.mean(dim=['south_north','west_east'])
    sn = xdata.SNOW_ACC_NC.mean(dim=['south_north','west_east'])
    psfc = xdata.PSFC.mean(dim=['south_north','west_east'])
    t2 = xdata.T2.mean(dim=['south_north','west_east'])
    u10 = xdata.U10.mean(dim=['south_north','west_east'])
    v10 = xdata.V10.mean(dim=['south_north','west_east'])
    rh2 = xdata.RH2.mean(dim=['south_north','west_east'])
    td2 = xdata.Td2.mean(dim=['south_north','west_east'])
    #xdata_mean = xdata.mean(dim=['XLAT','XLONG'])
    
    # populating the dataframe
    df['Time'] = time
    df[f'PR ({xdata.PREC_ACC_NC.units})'] = pr
    df[f'SN ({xdata.SNOW_ACC_NC.units})'] = sn
    df[f'PSFC ({xdata.PSFC.units})'] = psfc
    df[f'T2 ({xdata.T2.units})'] = t2
    df[f'U10 ({xdata.U10.units})'] = u10
    df[f'V10 ({xdata.V10.units})'] = v10
    df[f'TD2 ({xdata.Td2.units})'] = td2
    
    df.to_csv(fname)

/home/cruman/Data/CONUS_I/CONUSI@Stations/BAGOTVILLE A_QC/CTRL/BAGOTVILLE A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/BRANDON A_MB/CTRL/BRANDON A_MB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/CALGARY INT'L A_AB/CTRL/CALGARY INT'L A_AB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/CHARLOTTETOWN A_PE/CTRL/CHARLOTTETOWN A_PE_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/COLD LAKE A_AB/CTRL/COLD LAKE A_AB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/CRANBROOK A_BC/CTRL/CRANBROOK A_BC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/EDMONTON INT'L A_AB/CTRL/EDMONTON INT'L A_AB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/FREDERICTON A_NB/CTRL/FREDERICTON A_NB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/GASPE A_QC/CTRL/GASPE A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/GRANDE PRAIRIE A_AB/CTRL/GRANDE PRAIRIE A_AB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/HALIFAX STANFIELD INT'L A_NS/CTRL/HALIFAX STANFIELD INT'L A_NS_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/KAMLOOPS A_BC/CTRL/KAMLOOPS A_BC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/KAPUSKASING A_ON/CTRL/KAPUSKASING A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/KENORA A_ON/CTRL/KENORA A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/KUUJJUARAPIK A_QC/CTRL/KUUJJUARAPIK A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/LA GRANDE RIVIERE A_QC/CTRL/LA GRANDE RIVIERE A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/LA RONGE A_SK/CTRL/LA RONGE A_SK_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/MONT-JOLI A_QC/CTRL/MONT-JOLI A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/MONTREAL:PIERRE ELLIOTT TRUDEAU INTL A_QC/CTRL/MONTREAL:PIERRE ELLIOTT TRUDEAU INTL A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/NORTH BAY A_ON/CTRL/NORTH BAY A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/OTTAWA MACDONALD-CARTIER INT'L  A_ON/CTRL/OTTAWA MACDONALD-CARTIER INT'L  A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/PORT HARDY A_BC/CTRL/PORT HARDY A_BC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/QUEBEC:JEAN LESAGE INTL A_QC/CTRL/QUEBEC:JEAN LESAGE INTL A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/REGINA INT'L A_SK/CTRL/REGINA INT'L A_SK_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/ROUYN A_QC/CTRL/ROUYN A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/SASKATOON DIEFENBAKER INT'L A_SK/CTRL/SASKATOON DIEFENBAKER INT'L A_SK_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/SAULT STE MARIE A_ON/CTRL/SAULT STE MARIE A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/SEPT-ILES A_QC/CTRL/SEPT-ILES A_QC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/THE PAS A_MB/CTRL/THE PAS A_MB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/THOMPSON A_MB/CTRL/THOMPSON A_MB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/THUNDER BAY A_ON/CTRL/THUNDER BAY A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/TORONTO LESTER B. PEARSON INT'L A_ON/CTRL/TORONTO LESTER B. PEARSON INT'L A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/VANCOUVER INT'L A_BC/CTRL/VANCOUVER INT'L A_BC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/VICTORIA INT'L A_BC/CTRL/VICTORIA INT'L A_BC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/WABUSH LAKE A_NL/CTRL/WABUSH LAKE A_NL_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/WILLIAMS LAKE A_BC/CTRL/WILLIAMS LAKE A_BC_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/WINDSOR A_ON/CTRL/WINDSOR A_ON_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/WINNIPEG RICHARDSON INT'L A_MB/CTRL/WINNIPEG RICHARDSON INT'L A_MB_CTRL_wrf2d_d01.nc
/home/cruman/Data/CONUS_I/CONUSI@Stations/YARMOUTH A_NS/CTRL/YARMOUTH A_NS_CTRL_wrf2d_d01.nc

In [32]:
#xdata.mean(dim=['south_north','west_east'])
pr = xdata.PREC_ACC_NC.mean(dim=['south_north','west_east'])
sn = xdata.SNOW_ACC_NC.mean(dim=['south_north','west_east'])
psfc = xdata.PSFC.mean(dim=['south_north','west_east'])
t2 = xdata.T2.mean(dim=['south_north','west_east'])
u10 = xdata.U10.mean(dim=['south_north','west_east'])
v10 = xdata.V10.mean(dim=['south_north','west_east'])
rh2 = xdata.RH2.mean(dim=['south_north','west_east'])
t2d = xdata.Td2.mean(dim=['south_north','west_east'])

In [20]:
df['PR'] = pr.values

In [38]:
df

,Time,PR (mm),SN (mm),PSFC (Pa),T2 (K),U10 (m s-1),V10 (m s-1)
0,2000-10-01 00:00:00,0.000000e+00,0.0,99601.328125,289.468903,2.412105,3.258781
1,2000-10-01 01:00:00,0.000000e+00,0.0,99561.039062,289.362488,0.710587,1.806993
2,2000-10-01 02:00:00,0.000000e+00,0.0,99518.609375,289.933777,0.384283,0.923267
3,2000-10-01 03:00:00,9.209331e-09,0.0,99500.281250,289.818970,-0.586958,-0.421743
4,2000-10-01 04:00:00,1.135387e-03,0.0,99449.406250,289.957245,-0.793274,-0.914846
...,...,...,...,...,...,...,...
113782,2013-09-23 22:00:00,0.000000e+00,0.0,99512.781250,299.888245,-0.075984,-1.173766
113783,2013-09-23 23:00:00,0.000000e+00,0.0,99522.617188,299.893066,-0.495524,-0.917821
113784,2013-09-24 00:00:00,0.000000e+00,0.0,99528.960938,299.257446,-0.728832,-0.553541
113785,2013-09-24 01:00:00,0.000000e+00,0.0,99488.132812,296.726685,-1.551494,0.051221
113786,2013-09-24 02:00:00,0.000000e+00,0.0,99492.843750,293.437195,-2.166796,1.343893

In [42]:
time = []
di = datetime(2000,10,1,0,0)
for item in aux.Time:
    time.append(di + relativedelta(hours=int(item.values)))

In [47]:
xdata['Time'] = pd.DatetimeIndex(xdata['Time'].values)

In [53]:
time[-1]

datetime.datetime(2013, 10, 8, 0, 0)